"""What each of the 33 ops consumes and produces, for ``MANIFEST.json``.

A third-party runner reads this table, not this file: it is emitted into
``MANIFEST.ops`` so an implementer can tell, without reading Python, which ops
exist, which profile each belongs to, which input spellings it may see, which
output fields are compared, which of those are arrays whose order is
unconstrained, and which need a capability (zlib, Ed25519) they may not have.
"""

from __future__ import annotations

READER, WRITER, VERIFIER = "reader", "writer", "verifier"

#: op -> (profile, input spellings, args, output fields, unordered fields, requires)
OP_META: dict[str, dict[str, object]] = {
    "text.validate": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": [],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "refuse a document whose text holds an unpaired UTF-16 surrogate",
    },
    "canon.v3": {
        "profile": READER,
        "input": ["value"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 0.2 canonical bytes of a value",
    },
    "canon.v2": {
        "profile": READER,
        "input": ["value"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 0.3 canonical bytes of a value",
    },
    "shape.scan": {
        "profile": READER,
        "input": ["bytes_b64", "gen"],
        "args": ["max_tokens"],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "the SPEC 0.5 byte scanner: depth and structural-token bounds",
    },
    "envelope.decode": {
        "profile": READER,
        "input": ["bytes_b64", "blob"],
        "args": ["expected_oid"],
        "output": ["oid", "type", "schema", "encoding", "body_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.2 framing plus SPEC 1.3 oid derivation",
    },
    "envelope.encode": {
        "profile": WRITER,
        "input": ["value", "bytes_b64"],
        "args": ["header"],
        "output": ["bytes_b64", "oid"],
        "unordered": [],
        "requires": [],
        "summary": "the stored envelope bytes for a type, schema and payload",
    },
    "oid.derive": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": ["header"],
        "output": ["oid"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.3 framing: TYPE 0x00 SCHEMA 0x00 BODY, hashed",
    },
    "oid.parse": {
        "profile": READER,
        "input": ["value"],
        "args": [],
        "output": ["type", "digest"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.3 OID_RE",
    },
    "links.extract": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": ["present", "objects", "shallow"],
        "output": ["links"],
        "unordered": ["links"],
        "requires": [],
        "summary": "SPEC 1.5 link fields, their type rules, and their existence",
    },
    "event.metrics": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": [],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.5.2 cost/duration/time_unix/usage rules",
    },
    "run.graph": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": ["present", "objects"],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.5.3 status, ordering, legacy_refs, and exact roots/tips",
    },
    "annotation.chain": {
        "profile": READER,
        "input": ["bytes_b64"],
        "args": ["present", "objects"],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.5.5 previous_id chain rules",
    },
    "object.load": {
        "profile": READER,
        "input": ["bytes_b64", "path"],
        "args": ["expected_oid", "present", "objects", "shallow"],
        "output": ["oid", "links"],
        "unordered": ["links"],
        "requires": [],
        "summary": "one full local read: decode, links, metrics, graph and chain together",
    },
    "object.path": {
        "profile": READER,
        "input": ["value"],
        "args": [],
        "output": ["path"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.3 loose-object path derivation",
    },
    "config.validate": {
        "profile": READER,
        "input": ["bytes_b64", "gen"],
        "args": [],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.2 repository descriptor",
    },
    "ref.name": {
        "profile": READER,
        "input": ["value"],
        "args": [],
        "output": ["name"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.4 ref-name normalization and its bounds",
    },
    "ref.file": {
        "profile": READER,
        "input": ["bytes_b64", "gen"],
        "args": [],
        "output": ["oid"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.4 ref file bytes",
    },
    "ref.target": {
        "profile": READER,
        "input": ["value"],
        "args": ["name", "objects"],
        "output": [],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.5 typed-namespace target rules",
    },
    "reflog.row": {
        "profile": WRITER,
        "input": ["value"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.6 one canonical reflog row plus its LF",
    },
    "shallow.parse": {
        "profile": READER,
        "input": ["bytes_b64", "gen"],
        "args": [],
        "output": ["oids"],
        "unordered": ["oids"],
        "requires": [],
        "summary": "SPEC 2.7 shallow-boundary file",
    },
    "shallow.encode": {
        "profile": WRITER,
        "input": ["value"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.7 writer side: sorted, unique, LF-terminated",
    },
    "pack.inspect": {
        "profile": READER,
        "input": ["blob", "bytes_b64", "gen"],
        "args": [],
        "output": ["pack_id", "objects", "shallow"],
        "unordered": ["objects", "shallow"],
        "requires": ["zlib"],
        "summary": "SPEC 2.8 TINEPACK3 frame and manifest",
    },
    "pack.manifest": {
        "profile": WRITER,
        "input": ["value"],
        "args": [],
        "output": ["manifest_body_b64", "pack_id"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 2.8 writer side: the decompressed manifest and its id",
    },
    "pack.install": {
        "profile": WRITER,
        "input": ["blob", "bytes_b64"],
        "args": ["objects", "shallow"],
        "output": ["pack_id", "objects"],
        "unordered": ["objects"],
        "requires": ["zlib"],
        "summary": "SPEC 2.8 installation: link resolution and shallow-closure equality",
    },
    "artifact.parse": {
        "profile": READER,
        "input": ["bytes_b64", "blob", "gen", "path"],
        "args": [],
        "output": ["top_level_keys"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 3.1/3.7 .tine reader, including the parser differentials",
    },
    "integrity.digest": {
        "profile": READER,
        "input": ["bytes_b64", "blob", "path"],
        "args": [],
        "output": ["digest"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 3.5 digest over the parsed document minus metadata",
    },
    "integrity.verify": {
        "profile": READER,
        "input": ["bytes_b64", "blob", "path"],
        "args": [],
        "output": ["ok", "algorithm", "expected", "actual", "reason"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 3.5 consistency verdict -- never an authenticity claim",
    },
    "sig.message": {
        "profile": VERIFIER,
        "input": ["value"],
        "args": ["scheme", "key"],
        "output": ["message_b64", "value"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 4.2 signed message under one of the three schemes",
    },
    "sig.verify": {
        "profile": VERIFIER,
        "input": ["value", "bytes_b64", "path"],
        "args": ["family", "key", "public_key", "trust_embedded"],
        "output": ["ok", "state", "algorithm", "key_id", "signer", "signed_at", "reason"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 4.7 fail-closed verdict; raising is a failure",
    },
    "object.put": {
        "profile": WRITER,
        "input": ["value", "bytes_b64"],
        "args": ["objects", "schema", "type"],
        "output": ["oid", "body_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.4 before SPEC 1.3: redaction runs, then the oid names the result",
    },
    "attest.sign": {
        "profile": WRITER,
        "input": ["value"],
        "args": ["algorithm", "key", "key_id", "objects", "signed_at"],
        "output": ["oid", "body_b64", "signature"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 4.5: the signature covers the payload as stored, after redaction",
    },
    "redact.blob": {
        "profile": WRITER,
        "input": ["bytes_b64"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.4 credential redaction over raw blob bytes (optional)",
    },
    "redact.value": {
        "profile": WRITER,
        "input": ["value"],
        "args": [],
        "output": ["bytes_b64"],
        "unordered": [],
        "requires": [],
        "summary": "SPEC 1.4 credential redaction over decoded JSON (optional)",
    },
}
