"""Live external agent harness tests.

These tests are opt-in and run real CLI agents in disposable temp workspaces.
They skip when the requested CLI is not installed or is not authenticated.

Examples:

  pytest tests/test_live_harness.py -m live_harness --agent-harness codex
  pytest tests/test_live_harness.py -m live_harness --agent-harness opencode
  pytest tests/test_live_harness.py -m live_harness --agent-harness kimi-code
  pytest tests/test_live_harness.py -m live_harness --agent-harness openclaw
  pytest tests/test_live_harness.py -m live_harness --agent-harness hermes
  pytest tests/test_live_harness.py -m live_harness --agent-harness generic \
    --harness-command "your-agent run"
"""

from __future__ import annotations

import shlex
import shutil
import sys

import pytest

from opentine import Run, RunStatus, StepKind, cli
from opentine.harnesses import (
    ClaudeCodeHarness,
    CodexCLIHarness,
    GenericHarness,
    HermesHarness,
    KimiCodeHarness,
    OpenClawHarness,
    OpenCodeHarness,
    OpentineHarness,
    PiHarness,
)

pytestmark = pytest.mark.live_harness

HARNESS_FACTORIES = {
    "claude-code": ClaudeCodeHarness,
    "codex": CodexCLIHarness,
    "generic": GenericHarness,
    "hermes": HermesHarness,
    "kimi-code": KimiCodeHarness,
    "openclaw": OpenClawHarness,
    "opencode": OpenCodeHarness,
    "pi": PiHarness,
}

AUTH_FAILURE_TOKENS = (
    "auth",
    "authenticate",
    "login",
    "not logged in",
    "api key",
    "token",
    "credential",
)


def _selected_harnesses(config) -> list[str]:
    selected = config.getoption("--agent-harness")
    if selected == "all":
        return list(HARNESS_FACTORIES)
    if selected not in HARNESS_FACTORIES:
        pytest.skip(f"Unknown harness: {selected}")
    return [selected]


def _invoke(monkeypatch, *args: str) -> None:
    monkeypatch.setattr(sys, "argv", ["tine", *args])
    cli.main()


def test_live_agent_harness_records_and_cli_graph_ops(request, monkeypatch, tmp_path, capsys):
    selected = _selected_harnesses(request.config)
    ran = False
    for name in selected:
        command_override = request.config.getoption("--harness-command")
        command = tuple(shlex.split(command_override)) if command_override else None
        if name in {"generic", "pi"} and not command:
            pytest.skip(f"--harness-command is required for {name}")

        factory = HARNESS_FACTORIES[name]
        probe = command or factory.default_command
        if not probe or shutil.which(probe[0]) is None:
            if len(selected) == 1:
                pytest.skip(f"{probe[0] if probe else name} is not installed")
            continue

        repo = tmp_path / f"{name}-repo"
        repo.mkdir()
        (repo / "README.md").write_text("# fixture\n\nSmall disposable repo.\n", encoding="utf-8")
        (repo / "notes.txt").write_text("Do not edit this file.\n", encoding="utf-8")

        harness = factory(command=command, cwd=repo, login_env=True)
        wrapped = OpentineHarness(harness)
        out = tmp_path / f"{name}.tine"
        prompt = "Inspect this repo and summarize the files; do not edit."

        try:
            run = wrapped.run_sync(prompt, save_path=out)
        except RuntimeError as exc:
            message = str(exc).lower()
            recorded = "\n".join(
                str(step.inputs) for step in (wrapped.run.steps if wrapped.run else [])
            ).lower()
            if any(token in message or token in recorded for token in AUTH_FAILURE_TOKENS):
                if len(selected) == 1:
                    pytest.skip(f"{name} is installed but not authenticated")
                continue
            raise

        assert out.exists()
        assert run.status in {RunStatus.completed, RunStatus.failed}
        assert run.metadata["harness"] == name
        assert run.manifest["kind"] == "external-harness"
        assert run.manifest["harness"] == name
        assert any(step.kind == StepKind.model for step in run.steps)
        assert len(run.steps) >= 2

        forked = tmp_path / f"{name}-forked.tine"
        replayed = tmp_path / f"{name}-replayed.tine"

        _invoke(monkeypatch, "show", str(out))
        _invoke(monkeypatch, "fork", str(out), "--from-step", "0", "--save", str(forked))
        _invoke(monkeypatch, "replay", str(out), "--inspect")
        _invoke(monkeypatch, "replay", str(out), "--mode", "cache", "--save", str(replayed))
        _invoke(monkeypatch, "diff", str(out), str(forked))

        cached = Run.load(replayed)
        assert cached.metadata["replay"]["mode"] == "cache"
        assert forked.exists()
        ran = True

    if not ran:
        pytest.skip("No selected harness CLI was installed and authenticated")
    captured = capsys.readouterr()
    assert "Cached replay" in captured.out
