"""Cross-version backwards-compatibility gate: a newer opentine MUST read data
written by any release >= 0.3.0.

From v0.3.0 on, stored data is a compatibility contract. The fixtures under
``tests/fixtures/compat/vX_Y_Z/`` were produced by the REAL published
``opentine==X.Y.Z`` (installed from PyPI, not this tree) by
``scripts/gen_compat_fixtures.py`` and committed as golden inputs. This test
proves the CURRENT build still reads every one of them cleanly:

  * every ``.tine`` artifact loads and its integrity digest still verifies;
  * a signed artifact still verifies under the same key, in both stored
    signature shapes (full key_id/signer/signed_at, and bare);
  * the fork each release created loads and is never falsely rejected — for a
    pre-0.4.0 fork (id derived the old ``(parent, point)`` way, no recorded
    ``metadata.fork``) ``verify_fork_id`` must abstain, and for a 0.4.0+ fork,
    which records the fork act, it must confirm;
  * that release's v3 repository opens and ``load_run`` / ``fsck`` / ``search``
    / ``log`` all work, and the run reconstructs to the same content.

This is a permanent release gate. Each future release must add a sibling
``tests/fixtures/compat/vX_Y_Z/`` generated by that published release (see
``scripts/gen_compat_fixtures.py``) and one ``Golden`` row below, so a newer
opentine is always exercised against every stored-data shape it promises to
keep reading. Fixtures are never regenerated for an old release: their bytes
are the evidence.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

import pytest

from opentine import Repo, Run, StepKind
from opentine._fork_identity import verify_fork_id

COMPAT = Path(__file__).parent / "fixtures" / "compat"

# Fixed, documented key every golden set is signed with.
HMAC_KEY = b"compat-golden-signing-key-000001"

ARTIFACTS = (
    "artifact.tine",
    "artifact_signed.tine",
    "artifact_signed_fork_reason.tine",
    "fork.tine",
)

KINDS = [StepKind.model, StepKind.tool, StepKind.think, StepKind.done]


@dataclass(frozen=True)
class Golden:
    """One published release's golden set, with the identities it minted."""

    version: str
    fork_id: str
    repo_main_oid: str
    repo_fork_oid: str
    #: 0.4.0 gave the fork act a recorded identity (``metadata.fork``).
    fork_records_identity: bool

    @property
    def path(self) -> Path:
        return COMPAT / self.version

    def artifact(self, name: str) -> Path:
        return self.path / name


GOLDEN = (
    Golden(
        version="v0_3_0",
        fork_id="5fd5ce3f46155ecf9e56cc79b94ec9b481a315e04ac4ba810f3106e0a3dd5c78",
        repo_main_oid="run:sha256:523ad46b326fdf1857d74ab1ab482b835a5e39de0accfd6e6ff43497c7dd899d",
        repo_fork_oid="run:sha256:09c0db642a45c642da4dc2577edd2b66f40b9c7126f7be64d9f5f5ec2786dbf9",
        fork_records_identity=False,
    ),
    Golden(
        version="v0_4_0",
        fork_id="71e982e0a75fb5d830236f9fc1ef4b34d825694cf58bb2f9ad204f6572eccb9d",
        repo_main_oid="run:sha256:66a3d94df92a40849582687a188a76706b3083e71332364b542eee167961cdef",
        repo_fork_oid="run:sha256:ddc55f274d55b56272a64e1417ec277c4598010410b8b4321d11005129c93a90",
        fork_records_identity=True,
    ),
)

VERSIONED = pytest.mark.parametrize("golden", GOLDEN, ids=[item.version for item in GOLDEN])


# --- .tine artifacts ---------------------------------------------------------


@VERSIONED
@pytest.mark.parametrize("name", ARTIFACTS)
def test_every_released_artifact_loads_and_integrity_still_verifies(golden: Golden, name: str):
    path = golden.artifact(name)
    run = Run.load(path)
    assert run.steps, f"{golden.version}/{name}: no steps decoded"
    # The integrity digest was computed by that release; this canon must agree.
    result = Run.verify_integrity(path)
    assert result.ok, f"{golden.version}/{name}: digest does not verify under this build"


@VERSIONED
def test_multi_kind_artifact_content_survives(golden: Golden):
    run = Run.load(golden.artifact("artifact.tine"))
    assert run.id == f"compat-artifact-{golden.version}"
    assert [step.kind for step in run.steps] == KINDS
    assert run.system_prompt == "You are a careful release assistant."
    assert run.user_prompt == "Summarize what shipped in this release."
    assert set(run.tags) == {"release", "compat", "golden"}
    assert run.metadata.get("project") == "opentine"
    # The human turn lives in the transcript (StepKind has no `human`).
    assert run.transcript and run.transcript[0]["role"] == "user"
    tool = run.steps[1]
    assert tool.kind is StepKind.tool
    assert tool.tool_info.get("name") == "search"
    assert run.steps[0].model_info == "anthropic/claude-sonnet-5"


@VERSIONED
def test_signed_artifact_still_verifies(golden: Golden):
    path = golden.artifact("artifact_signed.tine")
    res = Run.verify_signature(path, hmac_key=HMAC_KEY)
    assert res.ok and res.state == "verified" and res.algorithm == "hmac-sha256"
    assert res.key_id == "compat-golden" and res.signer == "release-bot"
    assert res.signed_at == "2026-01-01T00:00:00Z"
    assert Run.verify_integrity(path).ok
    # A wrong key must still be a clean mismatch, not an exception.
    assert Run.verify_signature(path, hmac_key=b"x" * 32).state == "mismatch"


@VERSIONED
def test_signed_artifact_carrying_fork_reason_still_verifies(golden: Golden):
    """Releases emit metadata.fork_reason (their MCP fork) but do not sign it. If
    a later release folds fork_reason into the signed set, every genuine older
    signature over such a run flips to a false 'mismatch'. These fixtures were
    signed by the published release and must keep verifying — with a bare
    signature block (no key_id/signer/signed_at), the other stored shape."""
    path = golden.artifact("artifact_signed_fork_reason.tine")
    assert Run.load(path).metadata["fork_reason"] == "explored approach A"
    res = Run.verify_signature(path, hmac_key=HMAC_KEY)
    assert res.ok and res.state == "verified", (
        f"a genuine {golden.version} signature over a run carrying fork_reason "
        f"must verify, got {res.state}"
    )
    assert Run.verify_integrity(path).ok


@VERSIONED
def test_released_fork_loads_and_is_never_falsely_rejected(golden: Golden):
    """A fork is the one artifact whose *id* is a derived claim, so each release's
    fork must keep its id and keep the verdict that release's shape earns: pre-
    0.4.0 forks record no basis and must abstain (never 'tampered'), 0.4.0+ forks
    record one and must re-derive to exactly the id they were stored with."""
    path = golden.artifact("fork.tine")
    run = Run.load(path)
    assert run.id == golden.fork_id
    assert Run.verify_integrity(path).ok
    assert run.metadata.get("forked_from") == f"compat-fork-source-{golden.version}"
    assert "fork_point" in run.metadata
    assert [step.kind for step in run.steps] == KINDS[:2]

    if not golden.fork_records_identity:
        assert "fork" not in run.metadata
        assert verify_fork_id(run) is None
        return

    record = run.metadata["fork"]
    assert record["source"] == run.metadata["forked_from"]
    assert record["point"] == run.metadata["fork_point"]
    assert verify_fork_id(run) is True, f"{golden.version}: genuine fork act read as tampered"


# --- v3 repository -----------------------------------------------------------


@pytest.fixture(params=GOLDEN, ids=[item.version for item in GOLDEN])
def golden_repo(request, tmp_path: Path) -> tuple[Golden, Repo]:
    # Copy out of the source tree first: proves the repo is relocatable (a real
    # cross-version property) and keeps read-time reflog/ref writes off the
    # committed fixture. Being committed to git, the fixture is MISSING the empty
    # scratch dirs (packs/, indexes/, refs/tags/) git drops — Repo.open recreates
    # them, which is exactly the version-control round trip the store now
    # survives, so no manual reconstitution is needed.
    golden: Golden = request.param
    dest = tmp_path / "repo"
    shutil.copytree(golden.path / "repo", dest)
    return golden, Repo.open(dest)


def test_released_v3_repo_opens_and_load_run_reconstructs(golden_repo: tuple[Golden, Repo]):
    golden, repo = golden_repo
    main = repo.load_run("heads/main")
    assert main.id == f"compat-repo-source-{golden.version}"
    assert [step.kind for step in main.steps] == KINDS
    # Loadable by content-addressed oid as well as by ref.
    assert repo.load_run(golden.repo_main_oid).id == main.id
    fork = repo.load_run("heads/experiment")
    assert fork.id == golden.repo_fork_oid


def test_released_v3_repo_fsck_search_and_log(golden_repo: tuple[Golden, Repo]):
    golden, repo = golden_repo
    assert repo.fsck().ok

    results = repo.search()
    assert isinstance(results, list) and results
    assert golden.repo_main_oid in {result.run_id for result in results}

    entries = repo.log("heads/main")
    assert len(entries) == 4  # the four events of the reconstructed run
    assert all(entry.object_type == "event" for entry in entries)
