"""Cross-version backwards-compatibility gate: a newer opentine MUST read data
written by any release >= 0.3.0.

From v0.3.0 on, stored data is a compatibility contract. The fixtures under
``tests/fixtures/compat/v0_3_0/`` were produced by the REAL published
``opentine==0.3.0`` (installed from PyPI, not this tree) and committed as golden
inputs. This test proves the CURRENT build still reads them cleanly:

  * every 0.3.0 ``.tine`` artifact loads and its integrity digest still verifies;
  * a 0.3.0 signed artifact still verifies under the same key;
  * the 0.3.0-created fork loads AND ``verify_fork_id`` returns ``None`` for it —
    a pre-0.4.0 fork (id derived the old ``(parent, point)`` way, no recorded
    ``metadata.fork``) must never be falsely rejected as tampered;
  * a 0.3.0 v3 repository opens and ``load_run`` / ``fsck`` / ``search`` / ``log``
    all work, and the run reconstructs to the same content.

This is a permanent release gate. Each future release should add a sibling
``tests/fixtures/compat/vX_Y_Z/`` directory generated by that published release
and extend the parametrization below, so a newer opentine is always exercised
against every stored-data shape it promises to keep reading.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from opentine import Repo, Run, StepKind
from opentine._fork_identity import verify_fork_id

COMPAT = Path(__file__).parent / "fixtures" / "compat"
V0_3_0 = COMPAT / "v0_3_0"

# Fixed, documented key used to sign artifact_signed.tine with published 0.3.0.
HMAC_KEY = b"compat-golden-signing-key-000001"

# Stable identities recorded when the fixtures were generated by 0.3.0.
FORK_ARTIFACT_ID = "5fd5ce3f46155ecf9e56cc79b94ec9b481a315e04ac4ba810f3106e0a3dd5c78"
REPO_MAIN_OID = "run:sha256:523ad46b326fdf1857d74ab1ab482b835a5e39de0accfd6e6ff43497c7dd899d"
REPO_FORK_OID = "run:sha256:09c0db642a45c642da4dc2577edd2b66f40b9c7126f7be64d9f5f5ec2786dbf9"

ARTIFACTS = ("artifact.tine", "artifact_signed.tine", "fork.tine")


# --- .tine artifacts ---------------------------------------------------------


@pytest.mark.parametrize("name", ARTIFACTS)
def test_030_artifact_loads_and_integrity_still_verifies(name: str):
    path = V0_3_0 / name
    run = Run.load(path)
    assert run.steps, f"{name}: no steps decoded"
    # The integrity digest is computed by 0.3.0; the current canon must agree.
    result = Run.verify_integrity(path)
    assert result.ok, f"{name}: 0.3.0 integrity digest does not verify under this build"


def test_030_multi_kind_artifact_content_survives():
    run = Run.load(V0_3_0 / "artifact.tine")
    kinds = [step.kind for step in run.steps]
    assert kinds == [StepKind.model, StepKind.tool, StepKind.think, StepKind.done]
    assert run.system_prompt == "You are a careful release assistant."
    assert run.user_prompt == "Summarize what shipped in this release."
    assert set(run.tags) == {"release", "compat", "golden"}
    assert run.metadata.get("project") == "opentine"
    # The human turn lives in the transcript (StepKind has no `human`).
    assert run.transcript and run.transcript[0]["role"] == "user"
    tool = run.steps[1]
    assert tool.kind is StepKind.tool
    assert tool.tool_info.get("name") == "search"
    assert run.steps[0].model_info == "anthropic/claude-sonnet-5"


def test_030_signed_artifact_still_verifies():
    path = V0_3_0 / "artifact_signed.tine"
    res = Run.verify_signature(path, hmac_key=HMAC_KEY)
    assert res.ok and res.state == "verified" and res.algorithm == "hmac-sha256"
    assert res.key_id == "compat-golden" and res.signer == "release-bot"
    assert res.signed_at == "2026-01-01T00:00:00Z"
    assert Run.verify_integrity(path).ok
    # A wrong key must still be a clean mismatch, not an exception.
    assert Run.verify_signature(path, hmac_key=b"x" * 32).state == "mismatch"


def test_030_fork_loads_and_is_never_falsely_rejected():
    path = V0_3_0 / "fork.tine"
    run = Run.load(path)
    # It loads and keeps the id 0.3.0 minted with the old (parent, point) rule.
    assert run.id == FORK_ARTIFACT_ID
    assert Run.verify_integrity(path).ok
    # A pre-0.4.0 fork recorded lineage under forked_from/fork_point and carries
    # no metadata.fork record, so the 0.4.0 identity check must abstain.
    assert run.metadata.get("forked_from") == "compat-fork-source-v0_3_0"
    assert "fork_point" in run.metadata
    assert "fork" not in run.metadata
    assert verify_fork_id(run) is None


# --- v3 repository -----------------------------------------------------------


# Empty scratch directories that Repo.init creates but git cannot store (git
# does not track empty directories). Deep fsck's os.scandir(packs) raises
# FileNotFoundError when packs/ is absent — identical code in 0.3.0 and 0.4.0 —
# so these are reconstituted here to present a faithful on-disk 0.3.0 repo.
# This is git-transport bookkeeping, NOT a relaxation of any read assertion.
_INIT_EMPTY_DIRS = ("packs", "indexes", "refs/tags")


@pytest.fixture
def repo(tmp_path: Path) -> Repo:
    # Copy out of the source tree first: proves the repo is relocatable (a real
    # cross-version property) and keeps read-time reflog/ref writes off the
    # committed fixture.
    dest = tmp_path / "repo"
    shutil.copytree(V0_3_0 / "repo", dest)
    for name in _INIT_EMPTY_DIRS:
        (dest / ".tine" / name).mkdir(parents=True, exist_ok=True)
    return Repo.open(dest)


def test_030_v3_repo_opens_and_load_run_reconstructs(repo: Repo):
    main = repo.load_run("heads/main")
    assert main.id == "compat-repo-source-v0_3_0"
    assert [step.kind for step in main.steps] == [
        StepKind.model,
        StepKind.tool,
        StepKind.think,
        StepKind.done,
    ]
    # Loadable by content-addressed oid as well as by ref.
    assert repo.load_run(REPO_MAIN_OID).id == main.id
    fork = repo.load_run("heads/experiment")
    assert fork.id == REPO_FORK_OID


def test_030_v3_repo_fsck_search_and_log(repo: Repo):
    assert repo.fsck().ok

    results = repo.search()
    assert isinstance(results, list) and results
    assert REPO_MAIN_OID in {result.run_id for result in results}

    entries = repo.log("heads/main")
    assert len(entries) == 4  # the four events of the reconstructed run
    assert all(entry.object_type == "event" for entry in entries)
