"""OpenAI-compatible hosted and local provider adapters."""

from opentine.models._compat_hosted import (
    GLM,
    ZAI,
    DeepSeek,
    Grok,
    Groq,
    Hermes,
    Kimi,
    Ministral,
    Mistral,
    OpenRouter,
    Qwen,
    Together,
)
from opentine.models._compat_local import (
    VLLM,
    Jan,
    LlamaCpp,
    LMStudio,
    LocalAI,
    LocalOpenAICompatible,
    OpenAICompatible,
    Unsloth,
)
from opentine.models._compat_local_presets import (
    MLXLM,
    TGI,
    KoboldCpp,
    LiteLLM,
    LlamaCppPython,
    NvidiaNIM,
    SGLang,
    TensorRTLLM,
)

__all__ = [
    "DeepSeek",
    "GLM",
    "Grok",
    "Groq",
    "Hermes",
    "Jan",
    "Kimi",
    "KoboldCpp",
    "LlamaCpp",
    "LlamaCppPython",
    "LiteLLM",
    "LMStudio",
    "LocalAI",
    "LocalOpenAICompatible",
    "MLXLM",
    "Ministral",
    "Mistral",
    "NvidiaNIM",
    "OpenRouter",
    "OpenAICompatible",
    "Qwen",
    "SGLang",
    "TGI",
    "TensorRTLLM",
    "Together",
    "Unsloth",
    "VLLM",
    "ZAI",
]
